### ISSUE TITLE
When I change the enc file it accepts it restarts the router but telnet still doesn't work

### ISSUE THREAD

**Issue by Black-bucky** [itsyourap/JioFiber-Home-Gateway#7] opened 2022-05-01 08:37 UTC
I am running the firmware that was uploaded in your git repository and I'm using the steps correctly, the enc file generates does contain the necessary changes in the first line. But when I upload the following enc file, the router restarts (photo attached below) and reverts back to the original enc file.

Jiofiber - JCOW404

![IMG_20220501_135903.jpg](https://user-images.githubusercontent.com/87582568/166138473-2cc17744-eade-4136-ac10-904b4cf3f3de.jpg)

**Comment by itsyourap** [comment] 2022-05-03 10:12
Duplicate of #5

**Closed by itsyourap** 2022-05-03 10:12 UTC
