### ISSUE TITLE
api

### ISSUE THREAD

**Issue by test2a** [itsyourap/JioFiber-Home-Gateway#1] opened 2021-10-12 14:55 UTC
hi. 
i have been a jio fiber user for quite some time now and i feel pained in logging into the router to check stuff. 

my idea. is there a way to get api access or something, like from a get/post which we can use existing solutions like homeassistant and connect the same there. 
for example, i would like to see how many connected users i have on the router, the homeassistant would send a get request and get data from there or something like that.
just..... pushing ideas out

**Comment by test2a** [comment] 2021-10-13 03:23
I mean can't we use the web ui method? I assume it would be easier. 

I have a use case where I have to update port forwarding to a local ipv6 which keeps changing.

**Comment by itsyourap** [comment] 2021-10-13 17:00
Yes, it is possible but Using WEB-UI will take a lot of time to load coz it has to load all the html and JS to scrap the data! The JioHome solution is a direct api which will take a lot less time to load as compared to the WEB-UI Solution.

**Comment by Otus9051** [comment] 2021-11-07 15:35
Yes, you can host websites with IPv6, infact, I have already tried it, only caveat is, many people do not support IPv6.

**Comment by test2a** [comment] 2021-11-08 05:16
@Otus9051 what this project does is bypass the ipv6 thing. so it uses duckdns to get your ipv6, then its free for all. i used this to get assistance, SSH from a guy living in finland last time. 

the problem is when jio changes your IPV6, that new address has to be manually added to jio router config page to allow it outside access. if i can do it programatically, that would automate it completly.

**Comment by test2a** [comment] 2021-11-08 05:25
@Otus9051 just go through my projects linked and you would understand my problem.

**Comment by Otus9051** [comment] 2021-11-08 06:12
> the problem is when jio changes your IPV6, that new address has to be manually added to jio router config page to allow it outside access. if i can do it programatically, that would automate it completly.

For me tho, I have a JCO4032, I didn't have to do that, i just port forwarded it and it worked. I also used DuckDNS.

**Comment by test2a** [comment] 2021-11-08 06:53
@Otus9051 how do you do the port forwarding?   i want to know that bit

**Comment by Otus9051** [comment] 2021-11-09 05:04
Open WebUI -> Security -> Firewall -> Port Forwarding -> Add New -> Add your INTERNAL IP in the Destination Address -> Select Port and stuff -> Save
![image](https://user-images.githubusercontent.com/58171861/140865715-f1b96494-3ada-41a6-8600-cc6da93195d3.png)

**Comment by test2a** [comment] 2021-11-09 05:09
@Otus9051 yes exactly. i want some api to push data to this page programatically so i do not have to manually update it everytime the ipv6 changes. manually is fine and i do that but i want to automate it with bash or something

**Comment by Otus9051** [comment] 2021-11-09 05:10
You don't need to update it...

**Comment by Otus9051** [comment] 2021-11-09 05:14
If you are talking about the IP at DuckDNS, then yes you may need to automate it. If you are talking about the Internal IP, there is a trick to set a static internal IP for a particular MAC Address. Go to WebUI -> Network -> LAN -> LAN IPv4 Reserved IPs -> Add New -> Add your Computer Name (put it as whatever you like), your desired IP Address and MAC Address. 
![image](https://user-images.githubusercontent.com/58171861/140866489-34212b0e-cddb-4fb8-ad76-2dc6932dddbd.png)

**Comment by test2a** [comment] 2021-11-09 05:14
![Screenshot_20211109_104315](https://user-images.githubusercontent.com/39449563/140866486-336e12f9-f7cd-4596-9c77-89dfd829182a.png)

**Comment by test2a** [comment] 2021-11-09 05:14
i checked my home now.  i have set ipv6 address in the firewall

**Comment by test2a** [comment] 2021-11-09 05:15
i have to update it often manually because this ipv6 is changing and that new address needs to be put in this box

**Comment by Otus9051** [comment] 2021-11-09 05:15
You are in the wrong section

**Comment by test2a** [comment] 2021-11-09 05:15
what why....

**Comment by test2a** [comment] 2021-11-09 05:16
when i do this, the ipv6 is global accessible. what should i have done?

**Comment by Otus9051** [comment] 2021-11-09 05:17
I mean both work but going in Port Forward is better as you don't need to manually update it on your side, instead, you need to update it on DuckDNS' side

**Comment by test2a** [comment] 2021-11-09 05:17
![Screenshot_20211109_104728](https://user-images.githubusercontent.com/39449563/140866845-d7d34e47-1219-497a-b110-cb5faf532058.png)

**Comment by Otus9051** [comment] 2021-11-09 05:18
Do you have something like Discord where we can talk then fully summarize the topic? this place is getting messy as hell.

**Comment by test2a** [comment] 2021-11-09 05:18
sure. will matrix work?

**Comment by Otus9051** [comment] 2021-11-09 05:18
Yep. I am JustAWeirDev@matrix.org

**Comment by test2a** [comment] 2021-11-09 05:20
john. sent

**Comment by Otus9051** [comment] 2021-11-09 05:21
didnt get yet, oh wait maybe i gave you the wrong id its `@justaweirdev:matrix.org`

**Comment by test2a** [comment] 2021-11-09 05:22
i already sent to that address. check

**Comment by Otus9051** [comment] 2021-11-09 05:23
Element is drunk.

**Comment by test2a** [comment] 2021-11-09 05:24
@johnsdwf:matrix.org

**Comment by itsyourap** [comment] 2021-11-28 11:08
Couldn't manage to work with the SIP Credentials found in the [dbglog](https://github.com/itsyourap/JioFiber-Home-Gateway/blob/master/Instructions/Get-dbglogs-JioFiber-ONT-Home-Gateway.md). Please take a look at these files in the  [dbglog](https://github.com/itsyourap/JioFiber-Home-Gateway/blob/master/Instructions/Get-dbglogs-JioFiber-ONT-Home-Gateway.md) :-

```
JuiceLog.txt
JuiceConfig.cfg
FixedVoiceCcsXML.dat
```

These files do contain helpful information regarding the usage of SIP in the router but I am not able to reproduce it on my side. 

I am closing this issue for now.

**Closed by itsyourap** 2021-11-28 11:08 UTC
Labels: enhancement

**Comment by Swamygoud369** [comment] 2022-12-28 09:46
I recently installed jiofiber wired network for my projects. I got one WordPress project, which is to update the theme. I updated the theme after that I checked the updated website. I was unable to see the updated version of the website by using jiofiber net when I used another network I can see the updated theme. For this reason, I lost my project. So Software employees and software companies do not use jiofiber network.

**Comment by Swamygoud369** [comment] 2022-12-28 09:48
> Will try my best! I just need to figure out the Authorization UID that is used by JioHome application to map out the mesh devices.. It will take a bit of time as I need to decompile JioHome application and figure out how the UID is generated.


I recently installed jiofiber wired network for my projects. I got one WordPress project, which is to update the theme. I updated the theme after that I checked the updated website. I was unable to see the updated version of the website by using jiofiber net when I used another network I can see the updated theme. For this reason, I lost my project. So Software employees and software companies do not use jiofiber network.

**Comment by k4976** [comment] 2023-01-05 03:24
> Thanks for the suggestion. I would like to inform you that there is a limited number of APIs till now in JioFiber Firmware:-
> 
> 1. Login
> 2. Forced Login
> 3. Change password of user accounts
> 4. Getting the Wi-Fi SSIDs and Passwords
> 5. Getting the Device Topology (i.e., the connected devices)
> 6. Get Wi-Fi status (On or Off)
> 7. Get Mesh Status (On or Off)
> 8. Enable or Disable Wi-Fi
> 9. Enable or Disable Mesh
> 
> Also, I am trying to figure out how JioCall works right now. Will let you know if I find anything.

Bro have you get apis used in jiohome app, i need it because when i use web ui to get data from it many times all connected devices won't be shown or sometimes uptime, ipv4 or ipv6 ip also not available but devices is connected to jiofiber and internet is also working and when i request for lan clients stats it took to around 5< secs to get data from jiofiber

one thing also happend when i fetching data one time all connected devices shown and when i request 2nd time it won't be available and then again in 3rd request it's showing data device which is missing in 2nd request and uptime is also proper means it won't disconnect while 2nd request but still won't shown correctly

**Comment by itsyourap** [comment] 2023-01-05 06:34
@k4976 Please see #20 to know about the APIs
